config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'images#index'

  resources :users do
    resources :images
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :photo

  belongs_to :user

  validates :photo, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :photo
  validates_attachment :photo,
    content_type: { content_type: ["image/jpeg", "image/jpg", "image/gif", "image/png"] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!, except: [ :index, :show ]
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @image = @user.images.new
  end

  def create
    @user = User.find(params[:user_id])
    @image = @user.images.new(image_params)
    if @image.save
      redirect_to user_path(@image.user)
    else
      render :new
    end
  end

  private
  def image_params
    params.require(:image).permit(:title, :description, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter { :index, :show }

  def index
    @users = User.all
    @images = Image.all
  end

  def show
    @user = User.find(params[:id])
    @images = @user.images
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= form_for [@user, @image], html: { multipart: true } do |f| %>
<br>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
<br>
  <%= f.label :title %>
  <%= f.text_field :title %>
<br>
  <%= f.label :description %>
  <%= f.text_field :description %>
<br>
  <%= f.submit "Upload photo" %>

<% end %>

app/views/images/index.html.erb
<h2>Flickr</h2>

<% @images.each do |image| %>
  <%= image_tag(image.photo) %>
  <p><%= image.title %></p>
<% end %>

<br>

app/views/images/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlickrClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>
</div>


</body>
</html>

app/views/users/index.html.erb
<h2>hello</h2>


<% @users.each do |user| %>
  <%= link_to user.email, user_path(user) %>
<% end %>

app/views/users/show.html.erb
<h2>Welcome to my user page!</h2>

<% @user.images.each do |image| %>
  <%= image_tag(image.photo) %>
  <p><%= image.title %></p>
<% end %>


<%= link_to "Upload new photo", new_user_image_path(@user) %>